# Generated by Django 5.2.4 on 2025-07-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_bullet_points_product_country_of_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bullet_points',
            field=models.TextField(blank=True),
        ),
    ]
