# Generated by Django 5.2.4 on 2025-07-19 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_productattributeoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalue',
            name='value',
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productattributeoption'),
        ),
    ]
