# Generated by Django 5.2.4 on 2025-07-19 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_productattributevalue_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributeoption',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductAttributeOption',
        ),
        migrations.DeleteModel(
            name='ProductAttributeValue',
        ),
    ]
