# Generated by Django 5.2.4 on 2025-07-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_attribute_productattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
