# Generated by Django 5.2.4 on 2025-07-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
